### PR TITLE
[Accessibility] Use stop accessibility from NYCT Subway Station CSV

### PR DESCRIPTION
**Pull request by cedarbaum**
# Overview

The NYC Subway's static GTFS feed does not currently contain the `wheelchair_boarding` column for any stops. However, this data does exist as part of the supplementary [MTA Subway Stations](https://data.ny.gov/Transportation/MTA-Subway-Stations/39hk-dx4f/about_data) dataset, which is already used for determining trip headsigns.

Each station has 3 columns pertaining to ADA compliance:

1. `ADA` - whether the station is accessible. This can be 0 if its inaccessible, 1 if its accessible, or 2 if its partially accessible.
2. `ADA Northbound` - whether the stations northbound platform is accessible. This can be 0 if its inaccessible or 1 if it's accessible.
3. `ADA Southbound` - whether the stations southbound platform is accessible. This can be 0 if its inaccessible or 1 if its accessible.

Using the above information, we can amend the stop data for each stop/platform with accessibility information.

# Code changes

This PR modifies the `nyctsubwaycsv` updater to read in the ADA information for each station and update the corresponding stops/platforms accordingly.

# Testing

Unit test are added for both the parsing and update logic for the `nyctsubwaycsv` module. In addition to testing the new accessibility changes, these tests also do some basic testing of the headsign rule ETL logic that existed before.

# Caveats

There are a couple caveats with this change, which I would appreciate your input on @jamespfennell.

## Partially accessible stops

Some stations are partially accessible, which is a bit tricky to convey in GTFS at the parent station level. For example, the 49 St stop only is accessible on the northbound (uptown) platform. Currently, I set the parent stop's `wheelchair_boarding` column to `WheelchairBoarding_Possible` in such cases. I am basing this on the language in the [GTFS documentation](https://gtfs.org/schedule/reference/#stopstxt):

> For parentless stops:
> 0 or empty - No accessibility information for the stop.
> 1 - Some vehicles at this stop can be boarded by a rider in a wheelchair.
> 2 - Wheelchair boarding is not possible at this stop.

I think **Some vehicles** could be interpreted here to mean some platforms, but I could see how this could be confusing if, for example, you rollup platforms into a single station view. An alternative approach would be to keep the parent's `wheelchair_boarding` column as unspecified in such cases.

## Future conflicts with GTFS data

In the future, the MTA might update the static GTFS data with the `wheelchair_boarding` column. In this happens, Transiter will continue to use the CSV data and overwrite data from the GTFS feed. We either have to:

1. Be careful to remove this code when/if such a change is made _or_
2. Detect when the GTFS feed includes this column and then don't perform the CSV workaround

I think (2) is relatively easy, so I can make this change if we think it's the better design.

### CODE REVIEW

**Comment by jamespfennell** [comment]
Thanks for this! Overall LGTM. I agree that it's a bit of gnarly problem but you've clearly thought about it pretty comprehensibly and I think your approach is good.

One comment related to the other PR .... should the child stops of the platforms inherit the platforms wheelchair boarding value? 😬

**Review by jamespfennell — APPROVED** [review]

**Comment by jamespfennell** [comment]
Btw, are you aware or on the NYC transit Google group? (https://groups.google.com/g/mtadeveloperresources) I wonder if it's worth posting there to ask the MTA to include this information in the GTFS static feed. Their engineers are generally slammed so I'm not optimistic they would be able to...but maybe worth trying.

**Comment by cedarbaum** [comment]
Thanks for the review! I think I did find a design issue with this current approach unfortunately. It occurred to me that this current logic assumes that the static feed is always updated _before_ the CSV data. This might be true on the initial system install, but I think for the future daily updates there is no guarantee of the update order (please correct me if I am wrong here). And if the static data is updated after the CSV data, it will delete the wheelchair boarding column.

My initial thought for how to fix this was to create another table `supplemental_stop_data`, put the accessibility data from the CSV file there, and then join it with the stop table only when the `wheelchair_boarding` column is `null`. This keeps the updating logic completely independent, though does add a bit of complexity and some additional logic on the get/list stop queries.

Do you have any thoughts on the above issue and proposed solution? Am also open to other ideas to get around this update order issue if you have any.

> One comment related to the other PR .... should the child stops of the platforms inherit the platforms wheelchair boarding value? 😬

This I am not sure about - my interpretation of the `parent_station` field is that it can only refer to the top-level station, not a platform. It seems from the spec that the only stop type that can have a platform as a parent is a "Boarding Area" (reference: https://gtfs.org/schedule/reference/#stopstxt), which, interestingly, has no defined rules for how to behave with respect to the `wheelchair_boarding` column. But please let me know if you interpret this differently or see counterexamples of this assumption.

> Btw, are you aware or on the NYC transit Google group? (https://groups.google.com/g/mtadeveloperresources) I wonder if it's worth posting there to ask the MTA to include this information in the GTFS static feed. Their engineers are generally slammed so I'm not optimistic they would be able to...but maybe worth trying.

This is a good idea, will do! I have used this group before - I recently asked if we can [remove the API keys from the GTFS RT bus feeds](https://groups.google.com/g/mtadeveloperresources/c/KkFZL8DX9oE/m/hPNMtAXVAQAJ), since they appear to work without them, but haven't gotten an answer yet.

**Comment by cedarbaum** [comment]
After giving this some more thought, I think the easiest (though perhaps not most elegant) way to handle this is to just add a feed config option for whether to include accessibility info from a feed. This way the independence of feed updates doesn't need to be considered.

With the latest commit, accessibility data will need to be explicitly enabled in the CSV feed and disenabled on the static feed. By default, the static feed will be used, so this new behavior will be opt-in. We can consider changing the default system configuration for the subway to use the CSV data for now if that makes sense, or just document it.

In parallel, I do still need to post about possibly including this data in the static GTFS feed to see if there's a possibility there. Before this, I am working on a simple script to augment the GTFS data manually with the CSV data.

Let me know your thoughts when you have time!

**Comment by jamespfennell** [comment]
Sorry again for the late review!

Thanks for this, it looks good! In general what's nice about this PR is that all of the new complexity/code is in the NYC-subway-specific code. This is nice because ideally the general-case code should not become too complicated because of special edge cases. One idea (that I may try to do myself) is that we can probably avoid adding the new `UpdateStopWithoutWheelchairBoarding` query and instead add a boolean parameter to the existing `UpdateStop` query to control whether the wheelchair boarding value is set to the current value of the inputted balue.

> We can consider changing the default system configuration for the subway to use the CSV data for now if that makes sense, or just document it.

Yeah I think it would be good to change the default system config for the NYC subway to use your new code! Both because your new code make the data better, and also because it's great if all of the code in Transiter is being exercised all the time.

**Pull request merged**
